/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    animals: Animal;
    'emergency-cases': EmergencyCase;
    'vet-records': VetRecord;
    events: Event;
    volunteers: Volunteer;
    'needs-list': NeedsList;
    'transparency-reports': TransparencyReport;
    redirects: Redirect;
    search: Search;
    'audit-logs': AuditLog;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-query-presets': PayloadQueryPreset;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    animals: AnimalsSelect<false> | AnimalsSelect<true>;
    'emergency-cases': EmergencyCasesSelect<false> | EmergencyCasesSelect<true>;
    'vet-records': VetRecordsSelect<false> | VetRecordsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    'needs-list': NeedsListSelect<false> | NeedsListSelect<true>;
    'transparency-reports': TransparencyReportsSelect<false> | TransparencyReportsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-query-presets': PayloadQueryPresetsSelect<false> | PayloadQueryPresetsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('tr' | 'en') | ('tr' | 'en')[];
  globals: {
    header: Header;
    'site-settings': SiteSetting;
    'ui-strings': UiString;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'ui-strings': UiStringsSelect<false> | UiStringsSelect<true>;
  };
  locale: 'tr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Linkin nasıl görüneceğini seçin.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | {
        media: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBlock';
      }
    | ArchiveBlock
    | TimelineBlock
    | MissionBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  postCategory?: ('kurtarma' | 'tedavi' | 'gunluk' | 'duyuru' | 'etkinlik') | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Linkin nasıl görüneceğini seçin.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Linkin nasıl görüneceğini seçin.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  title: string;
  items?:
    | {
        time?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock".
 */
export interface MissionBlock {
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  goals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mission';
}
/**
 * Bakım altındaki sokak hayvanları kayıtları
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals".
 */
export interface Animal {
  id: number;
  _order?: string | null;
  name: string;
  photos?: (number | Media)[] | null;
  /**
   * Hayvanın kurtarılma hikayesi — ziyaretçiler bunu okuyacak
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  needs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'kedi' | 'kopek';
  age?: string | null;
  gender: 'erkek' | 'disi' | 'bilinmiyor';
  /**
   * Tedavide: aktif tedavi | Kalıcı Bakım: barınakta | Acil: acil müdahale
   */
  animalStatus: 'tedavide' | 'kalici-bakim' | 'acil';
  featured?: boolean | null;
  location?: string | null;
  /**
   * Kilogram cinsinden
   */
  weight?: number | null;
  /**
   * 15 haneli mikroçip numarası
   */
  microchipId?: string | null;
  isSpayed?: boolean | null;
  isVaccinated?: boolean | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Acil tedavi gerektiren vaka kampanyaları
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-cases".
 */
export interface EmergencyCase {
  id: number;
  _order?: string | null;
  title: string;
  animal?: (number | null) | Animal;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?: (number | Media)[] | null;
  beforePhoto?: (number | null) | Media;
  afterPhoto?: (number | null) | Media;
  /**
   * Toplam hedeflenen bağış miktarı (₺)
   */
  targetAmount: number;
  /**
   * Şu ana kadar toplanan bağış miktarı (₺)
   */
  collectedAmount?: number | null;
  caseStatus: 'aktif' | 'tamamlandi';
  /**
   * Her güncelleme sitede kronolojik olarak gösterilir
   */
  updates?:
    | {
        date?: string | null;
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vet-records".
 */
export interface VetRecord {
  id: number;
  _order?: string | null;
  animal: number | Animal;
  recordType: 'muayene' | 'asi' | 'kisirlastirma' | 'ameliyat' | 'tedavi' | 'kontrol';
  date: string;
  veterinarian?: string | null;
  clinic?: string | null;
  diagnosis?: string | null;
  treatment?: string | null;
  medications?:
    | {
        name: string;
        dosage?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  cost?: number | null;
  documents?: (number | Media)[] | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Etkinlikleri oluşturun ve yönetin
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  location?: string | null;
  /**
   * Etkinliğin başlangıç tarih ve saati
   */
  eventDate: string;
  /**
   * Boş bırakılabilir
   */
  endDate?: string | null;
  eventType?: ('sahiplendirme' | 'mama-toplama' | 'bakim-gunu' | 'egitim' | 'diger') | null;
  eventStatus?: ('yaklasan' | 'devam-ediyor' | 'tamamlandi' | 'iptal') | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Gönüllü başvurularını inceleyin ve onaylayın
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Birden fazla alan seçilebilir
   */
  areas?: ('besleme' | 'tedavi' | 'nakliye' | 'sahiplendirme' | 'etkinlik')[] | null;
  message?: string | null;
  applicationStatus?: ('beklemede' | 'onaylandi' | 'reddedildi') | null;
  appliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * İhtiyaç duyulan mama ve malzemelerin stok takibi
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "needs-list".
 */
export interface NeedsList {
  id: number;
  _order?: string | null;
  productName: string;
  brandDetail?: string | null;
  urgency: 'acil' | 'orta' | 'yeterli';
  stockStatus?: string | null;
  /**
   * Mevcut stok miktarı
   */
  currentStock?: number | null;
  /**
   * Hedeflenen minimum stok miktarı
   */
  targetStock: number;
  /**
   * Ürünün ölçü birimi
   */
  unit?: ('kutu' | 'kg' | 'adet') | null;
  priority?: ('acil' | 'yuksek' | 'orta' | 'dusuk') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparency-reports".
 */
export interface TransparencyReport {
  id: number;
  title: string;
  month: string;
  expenses?:
    | {
        category?: string | null;
        amount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Otomatik hesaplanır (giderlerin toplamı)
   */
  totalExpense?: number | null;
  /**
   * Otomatik hesaplanır (bağışların toplamı)
   */
  totalDonation?: number | null;
  donorList?:
    | {
        name?: string | null;
        amount?: number | null;
        id?: string | null;
      }[]
    | null;
  documents?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Bu alanı değiştirdiğinizde web sitesini yeniden derlemeniz gerekecektir.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'animals';
          value: number | Animal;
        } | null)
      | ({
          relationTo: 'emergency-cases';
          value: number | EmergencyCase;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'animals';
        value: number | Animal;
      }
    | {
        relationTo: 'emergency-cases';
        value: number | EmergencyCase;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  collection: string;
  action: 'create' | 'update' | 'delete' | 'read';
  documentId: string;
  timestamp: string;
  user?: (number | null) | User;
  /**
   * Changes made in this operation
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'tr' | 'en') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'animals';
        value: number | Animal;
      } | null)
    | ({
        relationTo: 'emergency-cases';
        value: number | EmergencyCase;
      } | null)
    | ({
        relationTo: 'vet-records';
        value: number | VetRecord;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'volunteers';
        value: number | Volunteer;
      } | null)
    | ({
        relationTo: 'needs-list';
        value: number | NeedsList;
      } | null)
    | ({
        relationTo: 'transparency-reports';
        value: number | TransparencyReport;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets".
 */
export interface PayloadQueryPreset {
  id: number;
  title: string;
  isShared?: boolean | null;
  access?: {
    read?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | User)[] | null;
    };
    update?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | User)[] | null;
    };
    delete?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (number | User)[] | null;
    };
  };
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  groupBy?: string | null;
  relatedCollection: 'posts' | 'animals' | 'emergency-cases' | 'events' | 'volunteers' | 'needs-list';
  /**
   * This is a temporary field used to determine if updating the preset would remove the user's access to it. When `true`, this record will be deleted after running the preset's `validate` function.
   */
  isTemp?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock_select".
 */
export interface MissionBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  image?: T;
  goals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  postCategory?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals_select".
 */
export interface AnimalsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  photos?: T;
  story?: T;
  needs?: T;
  type?: T;
  age?: T;
  gender?: T;
  animalStatus?: T;
  featured?: T;
  location?: T;
  weight?: T;
  microchipId?: T;
  isSpayed?: T;
  isVaccinated?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency-cases_select".
 */
export interface EmergencyCasesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  animal?: T;
  description?: T;
  photos?: T;
  beforePhoto?: T;
  afterPhoto?: T;
  targetAmount?: T;
  collectedAmount?: T;
  caseStatus?: T;
  updates?:
    | T
    | {
        date?: T;
        text?: T;
        photo?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vet-records_select".
 */
export interface VetRecordsSelect<T extends boolean = true> {
  _order?: T;
  animal?: T;
  recordType?: T;
  date?: T;
  veterinarian?: T;
  clinic?: T;
  diagnosis?: T;
  treatment?: T;
  medications?:
    | T
    | {
        name?: T;
        dosage?: T;
        duration?: T;
        id?: T;
      };
  cost?: T;
  documents?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  coverImage?: T;
  location?: T;
  eventDate?: T;
  endDate?: T;
  eventType?: T;
  eventStatus?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  areas?: T;
  message?: T;
  applicationStatus?: T;
  appliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "needs-list_select".
 */
export interface NeedsListSelect<T extends boolean = true> {
  _order?: T;
  productName?: T;
  brandDetail?: T;
  urgency?: T;
  stockStatus?: T;
  currentStock?: T;
  targetStock?: T;
  unit?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transparency-reports_select".
 */
export interface TransparencyReportsSelect<T extends boolean = true> {
  title?: T;
  month?: T;
  expenses?:
    | T
    | {
        category?: T;
        amount?: T;
        id?: T;
      };
  totalExpense?: T;
  totalDonation?: T;
  donorList?:
    | T
    | {
        name?: T;
        amount?: T;
        id?: T;
      };
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T;
  action?: T;
  documentId?: T;
  timestamp?: T;
  user?: T;
  changes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets_select".
 */
export interface PayloadQueryPresetsSelect<T extends boolean = true> {
  title?: T;
  isShared?: T;
  access?:
    | T
    | {
        read?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        update?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        delete?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
      };
  where?: T;
  columns?: T;
  groupBy?: T;
  relatedCollection?: T;
  isTemp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Başlık çubuğunda gösterilecek logo (opsiyonel — yoksa marka adı metin olarak gösterilir)
   */
  logo?: (number | null) | Media;
  /**
   * Logo yoksa veya alt metin olarak gösterilecek marka adı
   */
  brandName?: string | null;
  navItems?:
    | {
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
        };
        label: string;
        /**
         * Menü açıldığında gösterilecek görsel
         */
        image?: (number | null) | Media;
        /**
         * Bu öğeyi bağış butonu olarak işaretle
         */
        isCta?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Ana sayfa bölümlerini sıralayın, etkinleştirin veya devre dışı bırakın.
   */
  homepageBlocks?:
    | (
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            rotatingWords?:
              | {
                  word: string;
                  id?: string | null;
                }[]
              | null;
            leftImage?: (number | null) | Media;
            rightImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            enabled?: boolean | null;
            metrics?:
              | {
                  label: string;
                  value: string;
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeStats';
          }
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            founderImage?: (number | null) | Media;
            founderCaption?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeStory';
          }
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllLink?: string | null;
            photoCountTemplate?: string | null;
            /**
             * Aktivite kartlarının görüntülenme şekli
             */
            galleryVariant?: ('grid' | 'circular' | 'stacking') | null;
            activities?:
              | {
                  key: 'feeding' | 'treatment' | 'spaying' | 'emergency' | 'vaccination' | 'shelter';
                  title: string;
                  description?: string | null;
                  images?: (number | Media)[] | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeOurWork';
          }
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllLink?: string | null;
            limit?: number | null;
            /**
             * Hayvan kartlarının görüntülenme şekli
             */
            galleryVariant?: ('grid' | 'masonry' | 'circular') | null;
            adoptCta?: string | null;
            adoptCtaSecondaryLabel?: string | null;
            typeLabels?: {
              kedi?: string | null;
              kopek?: string | null;
            };
            statusLabels?: {
              tedavide?: string | null;
              kaliciBakim?: string | null;
              acil?: string | null;
            };
            genderLabels?: {
              erkek?: string | null;
              disi?: string | null;
              bilinmiyor?: string | null;
            };
            booleanLabels?: {
              spayedYes?: string | null;
              spayedNo?: string | null;
              vaccinatedYes?: string | null;
              vaccinatedNo?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeFeaturedAnimals';
          }
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllLink?: string | null;
            tickerText?: string | null;
            limit?: number | null;
            labels?: {
              codeRed?: string | null;
              case?: string | null;
              active?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeActiveEmergencies';
          }
        | {
            enabled?: boolean | null;
            slogan?: string | null;
            ibanTitle?: string | null;
            internationalTitle?: string | null;
            volunteerTitle?: string | null;
            volunteerDescription?: string | null;
            internationalPlaceholder?: string | null;
            labels?: {
              copy?: string | null;
              comingSoon?: string | null;
              ibanPlaceholder?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSupportCards';
          }
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllLink?: string | null;
            limit?: number | null;
            labels?: {
              needed?: string | null;
              inStock?: string | null;
              stockLevel?: string | null;
              priorityAcil?: string | null;
              priorityYuksek?: string | null;
              priorityOrta?: string | null;
              priorityDusuk?: string | null;
              unitKutu?: string | null;
              unitKg?: string | null;
              unitAdet?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeNeedsList';
          }
        | {
            enabled?: boolean | null;
            sectionTitle?: string | null;
            viewAllLabel?: string | null;
            viewAllLink?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeRecentPosts';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            description?: string | null;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeTransparencyBanner';
          }
      )[]
    | null;
  bankAccounts?:
    | {
        bankName: string;
        accountHolder: string;
        iban: string;
        currency?: ('TRY' | 'USD' | 'EUR') | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        type:
          | 'instagram'
          | 'x-twitter'
          | 'facebook'
          | 'youtube'
          | 'tiktok'
          | 'linkedin'
          | 'github'
          | 'website'
          | 'whatsapp'
          | 'phone'
          | 'email'
          | 'other';
        /**
         * Örn: Bluesky, Threads, Telegram
         */
        customType?: string | null;
        /**
         * URL, telefon numarası veya e-posta adresi
         */
        url: string;
        /**
         * Varsayılan platform adı yerine özel etiket
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  catsCount?: number | null;
  dogsCount?: number | null;
  treatedCount?: number | null;
  spayedCount?: number | null;
  vaccinatedCount?: number | null;
  feedingPointsCount?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-strings".
 */
export interface UiString {
  id: number;
  common?: {
    siteName?: string | null;
    search?: string | null;
    loading?: string | null;
    goHome?: string | null;
    notFound?: string | null;
    backToHome?: string | null;
  };
  layout?: {
    skipToContent?: string | null;
    siteTitle?: string | null;
    siteDescription?: string | null;
    header?: {
      home?: string | null;
      posts?: string | null;
      search?: string | null;
      animals?: string | null;
      emergency?: string | null;
      blog?: string | null;
      donate?: string | null;
      volunteer?: string | null;
      openMenu?: string | null;
      closeMenu?: string | null;
    };
    languageSwitcher?: {
      label?: string | null;
    };
    mobileMenu?: {
      title?: string | null;
    };
    footer?: {
      copyright?: string | null;
      bankInfo?: string | null;
      contactUs?: string | null;
      quickLinks?: string | null;
      international?: string | null;
      copyIban?: string | null;
      followUs?: string | null;
      description?: string | null;
    };
    breadcrumb?: {
      home?: string | null;
    };
    mobileDonate?: {
      cta?: string | null;
    };
  };
  search?: {
    title?: string | null;
    placeholder?: string | null;
    noResults?: string | null;
    modal?: {
      placeholder?: string | null;
      noResults?: string | null;
      shortcut?: string | null;
    };
  };
  posts?: {
    title?: string | null;
    readMore?: string | null;
    noPosts?: string | null;
  };
  animals?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    filter?: {
      all?: string | null;
      kedi?: string | null;
      kopek?: string | null;
      noResults?: string | null;
      tedavide?: string | null;
      kaliciBakim?: string | null;
      acil?: string | null;
    };
    detail?: {
      story?: string | null;
      needs?: string | null;
      photos?: string | null;
      type?: string | null;
      age?: string | null;
      gender?: string | null;
      status?: string | null;
      erkek?: string | null;
      disi?: string | null;
      bilinmiyor?: string | null;
      back?: string | null;
      donate?: string | null;
      noPhotos?: string | null;
      whatsappMessage?: string | null;
    };
    lightbox?: {
      close?: string | null;
      prev?: string | null;
      next?: string | null;
      imageOf?: string | null;
    };
  };
  emergency?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    activeCases?: string | null;
    collected?: string | null;
    target?: string | null;
    progress?: string | null;
    noActive?: string | null;
    completedCases?: string | null;
    donateButton?: string | null;
    detail?: {
      description?: string | null;
      updates?: string | null;
      beforeAfter?: string | null;
      before?: string | null;
      after?: string | null;
      relatedAnimal?: string | null;
      noUpdates?: string | null;
    };
  };
  donate?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    hero?: {
      title?: string | null;
      badge?: string | null;
      subtitle?: string | null;
    };
    iban?: {
      title?: string | null;
      bank?: string | null;
      accountHolder?: string | null;
      iban?: string | null;
      copy?: string | null;
      placeholder?: string | null;
    };
    international?: {
      title?: string | null;
      comingSoon?: string | null;
      placeholder?: string | null;
    };
    volunteer?: {
      title?: string | null;
      description?: string | null;
      cta?: string | null;
    };
    ticker?: {
      slogan1?: string | null;
      slogan2?: string | null;
      slogan3?: string | null;
      cats?: string | null;
      dogs?: string | null;
      treated?: string | null;
    };
    cards?: {
      title?: string | null;
      foodTitle?: string | null;
      foodDescription?: string | null;
      vetTitle?: string | null;
      vetDescription?: string | null;
      surgeryTitle?: string | null;
      surgeryDescription?: string | null;
    };
    faq?: {
      title?: string | null;
      q1?: string | null;
      a1?: string | null;
      q2?: string | null;
      a2?: string | null;
      q3?: string | null;
      a3?: string | null;
      q4?: string | null;
      a4?: string | null;
      q5?: string | null;
      a5?: string | null;
    };
    transparency?: {
      title?: string | null;
      description?: string | null;
      reports?: string | null;
    };
  };
  supplies?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    table?: {
      product?: string | null;
      brand?: string | null;
      urgency?: string | null;
      stock?: string | null;
    };
    urgency?: {
      acil?: string | null;
      orta?: string | null;
      yeterli?: string | null;
    };
    shipping?: {
      title?: string | null;
      description?: string | null;
      cargo?: string | null;
      inPerson?: string | null;
      online?: string | null;
    };
    sponsor?: {
      title?: string | null;
      description?: string | null;
      cta?: string | null;
    };
    empty?: string | null;
  };
  transparency?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    report?: {
      expenses?: string | null;
      totalExpense?: string | null;
      donations?: string | null;
      totalDonation?: string | null;
      category?: string | null;
      amount?: string | null;
      comparison?: string | null;
      documents?: string | null;
    };
    empty?: string | null;
    currency?: string | null;
  };
  blog?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    filter?: {
      all?: string | null;
      kurtarma?: string | null;
      tedavi?: string | null;
      gunluk?: string | null;
      duyuru?: string | null;
      etkinlik?: string | null;
    };
    readMore?: string | null;
    share?: {
      title?: string | null;
      twitter?: string | null;
      facebook?: string | null;
      whatsapp?: string | null;
      copy?: string | null;
      copied?: string | null;
    };
    tags?: string | null;
    empty?: string | null;
    back?: string | null;
  };
  volunteer?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    areas?: {
      title?: string | null;
      fosterTitle?: string | null;
      fosterDescription?: string | null;
      healthTitle?: string | null;
      healthDescription?: string | null;
      feedingTitle?: string | null;
      feedingDescription?: string | null;
      shelterTitle?: string | null;
      shelterDescription?: string | null;
    };
    stats?: {
      title?: string | null;
      volunteers?: string | null;
      animalsHelped?: string | null;
      feedingPoints?: string | null;
    };
    faq?: {
      title?: string | null;
      q1?: string | null;
      a1?: string | null;
      q2?: string | null;
      a2?: string | null;
      q3?: string | null;
      a3?: string | null;
      q4?: string | null;
      a4?: string | null;
    };
    cta?: {
      title?: string | null;
      description?: string | null;
      whatsappMessage?: string | null;
    };
  };
  vision?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    association?: {
      title?: string | null;
      description?: string | null;
    };
    shortTerm?: {
      title?: string | null;
      shelterTitle?: string | null;
      shelterDescription?: string | null;
      spayTitle?: string | null;
      spayDescription?: string | null;
      volunteersTitle?: string | null;
      volunteersDescription?: string | null;
      clinicTitle?: string | null;
      clinicDescription?: string | null;
    };
    longTerm?: {
      title?: string | null;
      ngoTitle?: string | null;
      ngoDescription?: string | null;
      vetClinicTitle?: string | null;
      vetClinicDescription?: string | null;
      fosterTitle?: string | null;
      fosterDescription?: string | null;
      awarenessTitle?: string | null;
      awarenessDescription?: string | null;
    };
    network?: {
      title?: string | null;
      description?: string | null;
    };
    cta?: {
      title?: string | null;
      description?: string | null;
      donate?: string | null;
      volunteer?: string | null;
    };
  };
  contact?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
    whatsapp?: {
      label?: string | null;
      description?: string | null;
      message?: string | null;
    };
    phone?: {
      label?: string | null;
      description?: string | null;
    };
    email?: {
      label?: string | null;
      description?: string | null;
    };
    instagram?: {
      label?: string | null;
      description?: string | null;
    };
  };
  notFound?: {
    title?: string | null;
    message?: string | null;
    goHome?: string | null;
    viewAnimals?: string | null;
    donate?: string | null;
  };
  home?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    instagram?: {
      title?: string | null;
      followUs?: string | null;
    };
    volunteerCta?: {
      title?: string | null;
      description?: string | null;
      cta?: string | null;
    };
  };
  ourWork?: {
    meta?: {
      title?: string | null;
      description?: string | null;
    };
    title?: string | null;
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  brandName?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        label?: T;
        image?: T;
        isCta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  homepageBlocks?:
    | T
    | {
        homeHero?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              content?: T;
              rotatingWords?:
                | T
                | {
                    word?: T;
                    id?: T;
                  };
              leftImage?: T;
              rightImage?: T;
              id?: T;
              blockName?: T;
            };
        homeStats?:
          | T
          | {
              enabled?: T;
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeStory?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              founderImage?: T;
              founderCaption?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        homeOurWork?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllLink?: T;
              photoCountTemplate?: T;
              galleryVariant?: T;
              activities?:
                | T
                | {
                    key?: T;
                    title?: T;
                    description?: T;
                    images?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeFeaturedAnimals?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllLink?: T;
              limit?: T;
              galleryVariant?: T;
              adoptCta?: T;
              adoptCtaSecondaryLabel?: T;
              typeLabels?:
                | T
                | {
                    kedi?: T;
                    kopek?: T;
                  };
              statusLabels?:
                | T
                | {
                    tedavide?: T;
                    kaliciBakim?: T;
                    acil?: T;
                  };
              genderLabels?:
                | T
                | {
                    erkek?: T;
                    disi?: T;
                    bilinmiyor?: T;
                  };
              booleanLabels?:
                | T
                | {
                    spayedYes?: T;
                    spayedNo?: T;
                    vaccinatedYes?: T;
                    vaccinatedNo?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeActiveEmergencies?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllLink?: T;
              tickerText?: T;
              limit?: T;
              labels?:
                | T
                | {
                    codeRed?: T;
                    case?: T;
                    active?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeSupportCards?:
          | T
          | {
              enabled?: T;
              slogan?: T;
              ibanTitle?: T;
              internationalTitle?: T;
              volunteerTitle?: T;
              volunteerDescription?: T;
              internationalPlaceholder?: T;
              labels?:
                | T
                | {
                    copy?: T;
                    comingSoon?: T;
                    ibanPlaceholder?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeNeedsList?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllLink?: T;
              limit?: T;
              labels?:
                | T
                | {
                    needed?: T;
                    inStock?: T;
                    stockLevel?: T;
                    priorityAcil?: T;
                    priorityYuksek?: T;
                    priorityOrta?: T;
                    priorityDusuk?: T;
                    unitKutu?: T;
                    unitKg?: T;
                    unitAdet?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeRecentPosts?:
          | T
          | {
              enabled?: T;
              sectionTitle?: T;
              viewAllLabel?: T;
              viewAllLink?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        homeTransparencyBanner?:
          | T
          | {
              enabled?: T;
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
      };
  bankAccounts?:
    | T
    | {
        bankName?: T;
        accountHolder?: T;
        iban?: T;
        currency?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        type?: T;
        customType?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  catsCount?: T;
  dogsCount?: T;
  treatedCount?: T;
  spayedCount?: T;
  vaccinatedCount?: T;
  feedingPointsCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-strings_select".
 */
export interface UiStringsSelect<T extends boolean = true> {
  common?:
    | T
    | {
        siteName?: T;
        search?: T;
        loading?: T;
        goHome?: T;
        notFound?: T;
        backToHome?: T;
      };
  layout?:
    | T
    | {
        skipToContent?: T;
        siteTitle?: T;
        siteDescription?: T;
        header?:
          | T
          | {
              home?: T;
              posts?: T;
              search?: T;
              animals?: T;
              emergency?: T;
              blog?: T;
              donate?: T;
              volunteer?: T;
              openMenu?: T;
              closeMenu?: T;
            };
        languageSwitcher?:
          | T
          | {
              label?: T;
            };
        mobileMenu?:
          | T
          | {
              title?: T;
            };
        footer?:
          | T
          | {
              copyright?: T;
              bankInfo?: T;
              contactUs?: T;
              quickLinks?: T;
              international?: T;
              copyIban?: T;
              followUs?: T;
              description?: T;
            };
        breadcrumb?:
          | T
          | {
              home?: T;
            };
        mobileDonate?:
          | T
          | {
              cta?: T;
            };
      };
  search?:
    | T
    | {
        title?: T;
        placeholder?: T;
        noResults?: T;
        modal?:
          | T
          | {
              placeholder?: T;
              noResults?: T;
              shortcut?: T;
            };
      };
  posts?:
    | T
    | {
        title?: T;
        readMore?: T;
        noPosts?: T;
      };
  animals?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        filter?:
          | T
          | {
              all?: T;
              kedi?: T;
              kopek?: T;
              noResults?: T;
              tedavide?: T;
              kaliciBakim?: T;
              acil?: T;
            };
        detail?:
          | T
          | {
              story?: T;
              needs?: T;
              photos?: T;
              type?: T;
              age?: T;
              gender?: T;
              status?: T;
              erkek?: T;
              disi?: T;
              bilinmiyor?: T;
              back?: T;
              donate?: T;
              noPhotos?: T;
              whatsappMessage?: T;
            };
        lightbox?:
          | T
          | {
              close?: T;
              prev?: T;
              next?: T;
              imageOf?: T;
            };
      };
  emergency?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        activeCases?: T;
        collected?: T;
        target?: T;
        progress?: T;
        noActive?: T;
        completedCases?: T;
        donateButton?: T;
        detail?:
          | T
          | {
              description?: T;
              updates?: T;
              beforeAfter?: T;
              before?: T;
              after?: T;
              relatedAnimal?: T;
              noUpdates?: T;
            };
      };
  donate?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        hero?:
          | T
          | {
              title?: T;
              badge?: T;
              subtitle?: T;
            };
        iban?:
          | T
          | {
              title?: T;
              bank?: T;
              accountHolder?: T;
              iban?: T;
              copy?: T;
              placeholder?: T;
            };
        international?:
          | T
          | {
              title?: T;
              comingSoon?: T;
              placeholder?: T;
            };
        volunteer?:
          | T
          | {
              title?: T;
              description?: T;
              cta?: T;
            };
        ticker?:
          | T
          | {
              slogan1?: T;
              slogan2?: T;
              slogan3?: T;
              cats?: T;
              dogs?: T;
              treated?: T;
            };
        cards?:
          | T
          | {
              title?: T;
              foodTitle?: T;
              foodDescription?: T;
              vetTitle?: T;
              vetDescription?: T;
              surgeryTitle?: T;
              surgeryDescription?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              q1?: T;
              a1?: T;
              q2?: T;
              a2?: T;
              q3?: T;
              a3?: T;
              q4?: T;
              a4?: T;
              q5?: T;
              a5?: T;
            };
        transparency?:
          | T
          | {
              title?: T;
              description?: T;
              reports?: T;
            };
      };
  supplies?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        table?:
          | T
          | {
              product?: T;
              brand?: T;
              urgency?: T;
              stock?: T;
            };
        urgency?:
          | T
          | {
              acil?: T;
              orta?: T;
              yeterli?: T;
            };
        shipping?:
          | T
          | {
              title?: T;
              description?: T;
              cargo?: T;
              inPerson?: T;
              online?: T;
            };
        sponsor?:
          | T
          | {
              title?: T;
              description?: T;
              cta?: T;
            };
        empty?: T;
      };
  transparency?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        report?:
          | T
          | {
              expenses?: T;
              totalExpense?: T;
              donations?: T;
              totalDonation?: T;
              category?: T;
              amount?: T;
              comparison?: T;
              documents?: T;
            };
        empty?: T;
        currency?: T;
      };
  blog?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        filter?:
          | T
          | {
              all?: T;
              kurtarma?: T;
              tedavi?: T;
              gunluk?: T;
              duyuru?: T;
              etkinlik?: T;
            };
        readMore?: T;
        share?:
          | T
          | {
              title?: T;
              twitter?: T;
              facebook?: T;
              whatsapp?: T;
              copy?: T;
              copied?: T;
            };
        tags?: T;
        empty?: T;
        back?: T;
      };
  volunteer?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        areas?:
          | T
          | {
              title?: T;
              fosterTitle?: T;
              fosterDescription?: T;
              healthTitle?: T;
              healthDescription?: T;
              feedingTitle?: T;
              feedingDescription?: T;
              shelterTitle?: T;
              shelterDescription?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              volunteers?: T;
              animalsHelped?: T;
              feedingPoints?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              q1?: T;
              a1?: T;
              q2?: T;
              a2?: T;
              q3?: T;
              a3?: T;
              q4?: T;
              a4?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              whatsappMessage?: T;
            };
      };
  vision?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        association?:
          | T
          | {
              title?: T;
              description?: T;
            };
        shortTerm?:
          | T
          | {
              title?: T;
              shelterTitle?: T;
              shelterDescription?: T;
              spayTitle?: T;
              spayDescription?: T;
              volunteersTitle?: T;
              volunteersDescription?: T;
              clinicTitle?: T;
              clinicDescription?: T;
            };
        longTerm?:
          | T
          | {
              title?: T;
              ngoTitle?: T;
              ngoDescription?: T;
              vetClinicTitle?: T;
              vetClinicDescription?: T;
              fosterTitle?: T;
              fosterDescription?: T;
              awarenessTitle?: T;
              awarenessDescription?: T;
            };
        network?:
          | T
          | {
              title?: T;
              description?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              donate?: T;
              volunteer?: T;
            };
      };
  contact?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
        whatsapp?:
          | T
          | {
              label?: T;
              description?: T;
              message?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              description?: T;
            };
        email?:
          | T
          | {
              label?: T;
              description?: T;
            };
        instagram?:
          | T
          | {
              label?: T;
              description?: T;
            };
      };
  notFound?:
    | T
    | {
        title?: T;
        message?: T;
        goHome?: T;
        viewAnimals?: T;
        donate?: T;
      };
  home?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        instagram?:
          | T
          | {
              title?: T;
              followUs?: T;
            };
        volunteerCta?:
          | T
          | {
              title?: T;
              description?: T;
              cta?: T;
            };
      };
  ourWork?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        title?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'pages'
      | 'posts'
      | 'media'
      | 'categories'
      | 'users'
      | 'animals'
      | 'emergency-cases'
      | 'vet-records'
      | 'events'
      | 'volunteers'
      | 'needs-list'
      | 'transparency-reports'
      | 'redirects'
      | 'search'
      | 'audit-logs'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'animals';
          value: number | Animal;
        } | null)
      | ({
          relationTo: 'emergency-cases';
          value: number | EmergencyCase;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  variant: 'info' | 'warning' | 'success' | 'error';
  title?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  url: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}