/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
export { GET, POST, DELETE, PATCH, PUT, OPTIONS } from "@payloadcms/next/routes"
